name: deployment

on:
  push:
    branches:
      - master
    paths:
      - 'GeomSharp/**'

jobs:
  build:
    name: Publish to Nuget library

    runs-on: windows-2019

    steps:
    - name: Checkout geom_sharp
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '6.x'

    - name: Nuget Pack and Push
      run: |
        $proj_dir = $(Join-Path $pwd GeomSharp)
        $pkg_spec_path = $(Join-Path $proj_dir GeomSharp.nuspec)
        echo "pkg_spec_path = $pkg_spec_path"
        $pkg_out_dir = $(Join-Path $proj_dir nupkg)
        echo "pkg_out_dir = $pkg_out_dir"
        [xml]$xmlElm = Get-Content -Path $pkg_spec_path 
        $xml_version = $xmlElm.package.metadata.version
        echo "version = $xml_version"
        nuget pack $pkg_spec_path -Properties Configuration=Release -OutputDirectory $pkg_out_dir
        echo "pkg_out_files = $(ls $pkg_out_dir)"
        nuget push "$pkg_out_dir\*.nupkg" -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate
      shell: pwsh