name: deployment

on:
  push:
    branches:
      - master
    paths:
      - 'GeomSharp/**'

jobs:
  build:
    name: Publish to Nuget library

    runs-on: windows-2019

    steps:
    - name: Checkout geom_sharp
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '6.x'

    - name: Nuget Pack and Push
      run: |
        $proj_dir = $(Join-Path $pwd GeomSharp)
        $pkg_spec_path = $(Join-Path $proj_dir GeomSharp.nuspec)
        Write-Host "pkg_spec_path = $pkg_spec_path"
        $pkg_out_dir = $(Join-Path $proj_dir nupkg)
        Write-Host "pkg_out_dir = $pkg_out_dir"
        [xml]$xmlElm = Get-Content -Path $pkg_spec_path 
        $xml_version = $xmlElm.package.metadata.version
        Write-Host "version = $xml_version"
        nuget pack $pkg_spec_path -Build -Symbols -Properties Configuration=Release -OutputDirectory $pkg_out_dir -IncludeReferencedProjects
        $pkg_out_file = $(ls $(Join-Path $pkg_out_dir *$xml_version.nupkg))[0].FullName
        Write-Host "package = $(ls $pkg_out_file)"
        $pkg_out_sym = $(ls $(Join-Path $pkg_out_dir *$xml_version.symbols.nupkg))[0].FullName
        Write-Host "symbols = $(ls $pkg_out_sym)"
        $target_repo = "nuget.org"
        nuget push $pkg_out_file -Source $target_repo -SkipDuplicate
        nuget push $pkg_out_sym -Source $target_repo -SymbolSource $target_repo -SkipDuplicate       
      shell: pwsh