name: deployment

on:
  push:
    branches:
      - master
    paths:
      - 'GeomSharp/**'

jobs:
  build:
    name: Publish to Nuget library

    runs-on: windows-2019

    steps:
    - name: Checkout geom_sharp
      uses: actions/checkout@v2

    - name: Set up MSVC compiler
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '6.x'

    - name: Nuget Pack and Push
      run: |
        .\deploy_to_nuget.ps1
      shell: pwsh
