name: nuget-package-upgrade

on:
  push:
    branches:
      - master
    paths:
      - 'GeomSharp/**'
  pull_request:
    paths:
      - 'GeomSharp/**'

jobs:
  build:
    name: Publish to Nuget library

    runs-on: windows-2019

    steps:
    - name: Checkout geom_sharp
      uses: actions/checkout@v2

    - name: Set up MSVC compiler
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        $proj_dir = $(Join-Path $pwd GeomSharp)
        echo "proj_dir = $proj_dir "
        ls $proj_dir
        $proj_path = $(Join-Path $proj_dir GeomSharp.cproj)
        echo "proj_path = $proj_path "
        msbuild $proj_path -t:build -restore -property:Configuration=Release
      shell: pwsh
    
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2
      
    - name: Test
      working-directory: geom_sharp/GeomSharpTests
      run: |
        $test_dir = $(Join-Path $pwd GeomSharpTests)
        echo "test_dir = $test_dir"
        $test_path = $(Join-Path $test_dir GeomSharpTests.cproj)
        echo "test_path = $test_path"
        msbuild $test_path -t:build -restore -property:Configuration=Release
        $test_dll_path = $(Join-Path $test_path GeomSharpTests\bin\Release\GeomSharpTests.dll)
        echo "test_dll_path = $test_dll_path"
        vstest.console.exe $test_dll_path --Blame
      shell: pwsh

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '6.x'

    - name: Get Build Version
      id: merge_params
      run: |
        $proj_dir = $(Join-Path $pwd GeomSharp)
        $pkg_spec_path = $(Join-Path $proj_dir GeomSharp.nuspec)
        [xml]$xmlElm = Get-Content -Path $pkg_spec_path 
        $old_version = $xmlElm.package.metadata.version
        $v = $old_version.Split(".")
        $new_version = $(-join ($v[0], '.', $v[1], '.', $v[2].Split("-")[0], '-', $(git rev-parse --short HEAD)))
        echo "BUILD_VERSION=$new_version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh


    - name: Nuget Pack
      id: merge_pack
      run: |
        $proj_dir = $(Join-Path $pwd GeomSharp)
        $pkg_spec_path = $(Join-Path $proj_dir GeomSharp.nuspec)
        $pkg_out_dir = $(Join-Path $proj_dir nupkg)
        nuget pack $pkg_spec_path -Properties Configuration=$build_config -Symbols -Version ${{ steps.merge_params.outputs.BUILD_VERSION }} -OutputDirectory $pkg_out_dir
        echo "PKG_DIR=$pkg_out_dir" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh


    - name: Nuget Push
      run: nuget push ${{ steps.merge_pack.outputs.PKG_DIR }}\*.nupkg -Source 'https://api.nuget.org/v3/index.json' 
